#!/usr/bin/env python3
"""Content-independent qualification for the V5.3 3-state action-readiness
observer (src/metacom_pm/v1_5_v5_3_action_readiness.py).

Script 61 (the other session's audit) validated INVITES_ACTION/DECLINES_ACTION
recognition only on already-consumed V3/V5.2 construction rows -- the same
synthetic templates the regex's own phrasing was checked against while it was
being written ("I am open to one small reversible experiment", "What should I
do?"). Its own docstring already discloses this is a dev-replay result, not
generalization evidence (see ledger V15-MEAS-53).

This script is the actual content-independent qualification: it draws a fixed,
reproducible random sample of real EvoEmo seeker turns (naturalistic human
text, never used to author or tune the regex) from all 18 users, and compares
the observer's predictions against a real, honestly-assigned manual label per
turn (labeled by reading each turn in isolation -- i.e. with exactly the
information observe_action_readiness() itself has access to, no supporter
context). Manual labels are embedded as a fixed dict below (not regenerated by
this script) so this is a real, frozen human judgment, not a self-grading loop.

Zero API calls.
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from metacom_pm.io import write_json  # noqa: E402
from metacom_pm.v1_5_v5_3_action_readiness import (  # noqa: E402
    ActionReadiness,
    observe_action_readiness,
)

EVOEMO_PATH = ROOT / "data/external/evo_emo.json"
OUT_PATH = ROOT / "outputs/pm_v1_5_v5_3_me_action_readiness_content_independent_qualification_v1/report.json"

SAMPLE_SIZE = 70
MIN_LEN, MAX_LEN = 25, 400
SEED = 42

# Frozen manual labels, assigned by reading each sampled turn in isolation
# (same information observe_action_readiness() sees). 68/70 real, naturally
# occurring turns carry no explicit action-readiness cue at all -- expected,
# since this is a rare, specific speech act in real conversation, not
# something every turn signals.
MANUAL_LABELS = {
    0: "UNKNOWN", 1: "UNKNOWN", 2: "UNKNOWN", 3: "UNKNOWN", 4: "UNKNOWN",
    5: "UNKNOWN", 6: "UNKNOWN", 7: "UNKNOWN", 8: "UNKNOWN", 9: "UNKNOWN",
    10: "UNKNOWN", 11: "UNKNOWN", 12: "UNKNOWN", 13: "UNKNOWN", 14: "UNKNOWN",
    15: "UNKNOWN", 16: "UNKNOWN", 17: "UNKNOWN", 18: "UNKNOWN", 19: "UNKNOWN",
    20: "INVITES_ACTION", 21: "UNKNOWN", 22: "UNKNOWN", 23: "UNKNOWN", 24: "UNKNOWN",
    25: "UNKNOWN", 26: "UNKNOWN", 27: "UNKNOWN", 28: "UNKNOWN", 29: "UNKNOWN",
    30: "UNKNOWN", 31: "UNKNOWN", 32: "UNKNOWN", 33: "UNKNOWN", 34: "UNKNOWN",
    35: "UNKNOWN", 36: "UNKNOWN", 37: "UNKNOWN", 38: "UNKNOWN", 39: "UNKNOWN",
    40: "UNKNOWN", 41: "UNKNOWN", 42: "UNKNOWN", 43: "UNKNOWN", 44: "UNKNOWN",
    45: "UNKNOWN", 46: "UNKNOWN", 47: "UNKNOWN", 48: "UNKNOWN", 49: "UNKNOWN",
    50: "UNKNOWN", 51: "UNKNOWN", 52: "UNKNOWN", 53: "UNKNOWN", 54: "UNKNOWN",
    55: "UNKNOWN", 56: "UNKNOWN", 57: "UNKNOWN", 58: "UNKNOWN", 59: "UNKNOWN",
    60: "UNKNOWN", 61: "UNKNOWN", 62: "INVITES_ACTION", 63: "UNKNOWN", 64: "UNKNOWN",
    65: "UNKNOWN", 66: "UNKNOWN", 67: "UNKNOWN", 68: "UNKNOWN", 69: "UNKNOWN",
}


def sample_turns() -> list[tuple[str, str, int, str]]:
    users = json.loads(EVOEMO_PATH.read_text(encoding="utf-8"))
    turns: list[tuple[str, str, int, str]] = []
    for u in users:
        for sess in u.get("dialog_history") or []:
            for t in sess.get("dialogue", []):
                if t.get("role") != "seeker":
                    continue
                content = (t.get("content") or "").strip()
                if MIN_LEN <= len(content) <= MAX_LEN:
                    turns.append((u["id"], sess.get("id"), t["idx"], content))
    rng = random.Random(SEED)
    return rng.sample(turns, SAMPLE_SIZE)


def main() -> None:
    sample = sample_turns()
    rows = []
    confusion: dict[str, dict[str, int]] = {}
    for i, (uid, sid, idx, text) in enumerate(sample):
        manual = MANUAL_LABELS[i]
        predicted = observe_action_readiness(text).value
        confusion.setdefault(manual, {}).setdefault(predicted, 0)
        confusion[manual][predicted] += 1
        rows.append(
            {
                "index": i, "user_id": uid, "session_id": sid, "turn_idx": idx,
                "text": text, "manual_label": manual, "predicted_label": predicted,
                "agrees": manual == predicted,
            }
        )

    n = len(rows)
    agree = sum(r["agrees"] for r in rows)
    manual_invites = [r for r in rows if r["manual_label"] == "INVITES_ACTION"]
    manual_declines = [r for r in rows if r["manual_label"] == "DECLINES_ACTION"]
    manual_unknown = [r for r in rows if r["manual_label"] == "UNKNOWN"]
    false_invites = [
        r for r in rows if r["predicted_label"] == "INVITES_ACTION" and r["manual_label"] != "INVITES_ACTION"
    ]
    false_declines = [
        r for r in rows if r["predicted_label"] == "DECLINES_ACTION" and r["manual_label"] != "DECLINES_ACTION"
    ]

    report = {
        "protocol": "pm-v1.5-v5.3-me-action-readiness-content-independent-qualification-v1",
        "source": "real EvoEmo seeker turns, naturalistic text never used to author/tune the regex",
        "sample_size": n,
        "seed": SEED,
        "overall_agreement_rate": agree / n,
        "manual_label_distribution": {
            "INVITES_ACTION": len(manual_invites),
            "DECLINES_ACTION": len(manual_declines),
            "UNKNOWN": len(manual_unknown),
        },
        "confusion_matrix": confusion,
        "invites_recall": (
            sum(1 for r in manual_invites if r["agrees"]) / len(manual_invites)
            if manual_invites else None
        ),
        "declines_recall": (
            sum(1 for r in manual_declines if r["agrees"]) / len(manual_declines)
            if manual_declines else None
        ),
        "unknown_precision_as_default": (
            sum(1 for r in manual_unknown if r["agrees"]) / len(manual_unknown)
            if manual_unknown else None
        ),
        "false_positive_invites_action": [
            {"index": r["index"], "text": r["text"], "manual_label": r["manual_label"]}
            for r in false_invites
        ],
        "false_positive_declines_action": [
            {"index": r["index"], "text": r["text"], "manual_label": r["manual_label"]}
            for r in false_declines
        ],
        "rows": rows,
        "api_calls": 0,
    }
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    write_json(OUT_PATH, report)
    print(json.dumps({k: v for k, v in report.items() if k != "rows"}, indent=2))


if __name__ == "__main__":
    main()
